# Dockerfile.worker
FROM python:3.10
WORKDIR /code

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# Run Celery worker
CMD ["celery", "-A", "app.worker.celery_worker", "worker", "--loglevel=info"]
